full_repository_name: "gorda/gorda.io"
verbose: false
maintainers:
  - "GuangmingLuo"
  - "gorda"
  - "ikingye"
  - "malphi"
  - "rootsongjc"
  - "stormgbs"
  - "sunny0826"
  - "wangfakang"
  - "zhaohuabing"
detection_at: "09:00"
skip_weekend: true
flows:
  # /accept 指令
  - name: "/accept"
    permission:
      - "maintainers"
      - "member"
    current_label:
      - "status/pending"
    remove_label:
      - "status/pending"
    target_label:
      - "status/waiting-for-pr"
    success_feedback: "Thank you @somebody, this issue had been assigned to you."
    target_limit: 10
    limit_feedback: "Sorry @somebody, We found that you have claimed @count issues, in order to ensure the quality of each issue, please complete those before claiming new one."
    current_column_id: 9001
    target_column_id: 9002
    target_position: "top"
  # /delay-reset
  # 延期的策略
  - name: "/delay-reset"
    permission:
      - "maintainers"
      - "self"
    current_label:
      - "status/stale"
    job_name: "reset"
    delay: 7
    success_feedback: "@somebody, The reset date for this issue has been delay to @reset-date. Before the issue is reset, you can repeat enter `/delay-reset` to continue delaying the reset date."
  # /pushed 指令
  - name: "/pushed"
    permission:
      - "maintainers"
      - "self"
    current_label:
      - "status/waiting-for-pr"
    remove_label:
      - "status/waiting-for-pr"
      - "status/stale"
    target_label:
      - "status/reviewing"

  # /merged 指令
  - name: "/merged"
    permission:
      - "maintainers"
      - "self"
    current_label:
      - "status/reviewing"
    remove_label:
      - "status/reviewing"
    target_label:
      - "status/merged"
    close: true

  # /init 指令
  - name: "/init"
    permission:
      - "maintainers"
    target_label:
      - "kind/page"
      - "release/v0.3"
      - "status/pending"

  # /assign
  - name: "/assign"
    permission:
      - "maintainers"
    mentation: "addition"

  # /unassign 指令，解除分配
  - name: "/unassign"
    permission:
      - "maintainers"
      - "self"
    mentation: "remove"
jobs:
  - name: "warn"
    in: 14 # 天数，对于想要预先填充，但不生效的 job，可以将该值置为负数
    labels: # 在该状态停留超过一定时间，则提醒
      - "status/waiting-for-pr"
    target_label:  # 添加该 label
      - "status/stale"
    assignees_policy: "@keep_all"
    feedback: "@somebody, The Issue will be reset after @reset-date, please complete the Issue as soon as possible, you can also enter `/delay-reset` to delay the reset time."
  - name: "reset"
    in: 14
    instruct_name: "/delay-reset"
    labels: # 在该状态停留超过一定时间，则释放 issue
      - "status/stale"
    remove_labels: # 移除该 label
      - "status/stale"
      - "status/waiting-for-pr"
    target_label:  # 添加该 label
      - "status/pending"
    assignees_policy: "@remove_all"
    current_column_id: 9002 # Project 恢复到原来的 column
    target_column_id: 9001
    target_position: "top"
    warn_feedback: "@somebody, The Issue will be reset after @reset-date, please complete the Issue as soon as possible, you can also enter `/delay-reset` to delay the reset time."
    feedback: "Everyone can accept this issue now."
port: ":8080"
log_dir: "./log/"
log_file: "hook.log"
std_out_file: "hook.std.log"