full_repository_name: "gorda/gorda.io"
verbose: false
maintainers:
  - "GuangmingLuo"
  - "gorda"
  - "ikingye"
  - "malphi"
  - "rootsongjc"
  - "stormgbs"
  - "sunny0826"
  - "wangfakang"
  - "zhaohuabing"
detection_at: "09:00"
skip_weekend: true
flows:
  # /accept 指令
  - name: "/accept"
    permission:
      - "maintainers"
      - "member"
    current_label:
      - "status/pending"
    remove_label:
      - "status/pending"
    target_label:
      - "status/waiting-for-pr"
    success_feedback: "Thank you @somebody, this issue had been assigned to you."
    target_limit: 10
    limit_feedback: "Sorry @somebody, We found that you have claimed @count issues, in order to ensure the quality of each issue, please complete those before claiming new one."
    current_column_id: 9001
    target_column_id: 9002
    target_position: "top"
  # /delay-reset
  # 延期的策略
  - name: "/delay-reset"
    permission:
      - "maintainers"
      - "self"
    current_label:
      - "status/stale"
    job_name: "reset"
    # status/stale 状态的限制时间，在最后一次发送该指令的时间的基础上，延长的 extend 天数。
    # 例如：extend 是 7 天，4 月 13 日 进入 status/stale 状态，该状态的限制时间为 14 天，则该 issue 会在 4 月 27 日被
    # 重置。如果用户在 4 月 15 日发送 /delay-reset 指令，则表示延长至 4 月 22 日，由于这个日期早于预期重置日期，则
    # 不生效，检测时会以 4 月 27 日为准。如果用户在 4 月 26 日发送 /delay-reset 指令，则表示延长至 5 月 3 日，此时会生效，检测时会以 5 月 3 日为准。
    delay: 7
    success_feedback: "@somebody, The reset date for this issue has been delay to @reset-date. Before the issue is reset, you can repeat enter `/delay-reset` to continue delaying the reset date."
  # /pushed 指令
  - name: "/pushed"
    permission:
      - "maintainers"
      - "self"
    current_label:
      - "status/waiting-for-pr"
    remove_label:
      - "status/waiting-for-pr"
      - "status/stale"
    target_label:
      - "status/reviewing"

  # /merged 指令
  - name: "/merged"
    permission:
      - "maintainers"
      - "self"
    current_label:
      - "status/reviewing"
    remove_label:
      - "status/reviewing"
    target_label:
      - "status/merged"
    close: true

  # /init 指令
  - name: "/init"
    permission:
      - "maintainers"
    target_label:
      - "kind/page"
      - "release/v0.3"
      - "status/pending"

  # /assign
  - name: "/assign"
    permission:
      - "maintainers"
    mentation: "addition"

  # /unassign 指令，解除分配
  - name: "/unassign"
    permission:
      - "maintainers"
      - "self"
    mentation: "remove"
jobs:
  - name: "warn"
    in: 14 # 天数，对于想要预先填充，但不生效的 job，可以将该值置为负数
    labels: # 在该状态停留超过一定时间，则提醒
      - "status/waiting-for-pr"
    target_label:  # 添加该 label
      - "status/stale"
    assignees_policy: "@keep_all"
    # 提醒日期可能会被延长，但最终时期可以计算，提醒策略不变。
    # 先获取进入该状态的日期、当前日期、重置日期。
    # 重置日期 - 进入该状态的日期，得到的天数，基于倒数天数，每次翻倍的规律进行重复提醒。
    # 例如：一个共计 14 天后会被重置的任务，除首次提醒外，会在倒数第 1、2、4、8 天进行提醒。
    feedback: "@somebody, The Issue will be reset after @reset-date, please complete the Issue as soon as possible, you can also enter `/delay-reset` to delay the reset time."
  - name: "reset"
    in: 14
    # 该指令可以延长重置日期
    instruct_name: "/delay-reset"
    labels: # 在该状态停留超过一定时间，则释放 issue
      - "status/stale"
    remove_labels: # 移除该 label
      - "status/stale"
      - "status/waiting-for-pr"
    target_label:  # 添加该 label
      - "status/pending"
    assignees_policy: "@remove_all"
    current_column_id: 9002 # Project 恢复到原来的 column
    target_column_id: 9001
    target_position: "top"
    warn_feedback: "@somebody, The Issue will be reset after @reset-date, please complete the Issue as soon as possible, you can also enter `/delay-reset` to delay the reset time."
    feedback: "Everyone can accept the issue now."
port: ":8080"
log_dir: "./log/"
log_file: "hook.log"
std_out_file: "hook.std.log"