apiVersion: "v1"
kind: "Repository"
metadata:
  name: "gbe.3ks.dev"
spec:
  source:
    owner: "mmcgrana"
    repository: "gobyexample"
    site: "gobyexample.com"
    removePrefix: "examples"
  translate:
    owner: "gobyexample-cn"
    repository: "gobyexample"
    site: "gobyexample-cn.github.io"
  workspace:
    owner: "1kib"
    repository: "gbe"
    maintainerTeam: "gbe-maintainer"
    detection:
      at: "09:00"
      prIssue: 1
      addLabel:
      - "status/need-sync"
      deprecatedLabel:
      - "status/need-confirm"
  port: ":8080"
  logLevel: "dev"
  verbose: false
---
apiVersion: "v1"
kind: "IssueCreate"
metadata:
  name: "issue-create"
spec:
  prefix: "examples"
  fileType:
    - "go"
    - "sh"
  labels:
  - "kind/page"
  assignees:
  - "3ks"
  content: "examples"
  includes:
  # 即所有文件
  - path: ""
    labels:
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-sync"
spec:
  rules:
    instruct: "synced"
    permissions:
    - "@maintainer"
    - "@assigner"
    labels:
    - "status/need-sync"
  action:
    removeLabels:
    - "status/need-sync"
    failFeedback: "ooops, there are some accidents here, please provide `@req-id` to maintainer to help solve the problem."
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-grad"
spec:
  rules:
    instruct: "grad"
    permissions:
    - "@maintainer"
    labels:
    - "status/need-confirm"
  action:
    state: "closed"
    addLabels:
    - "status/graduated"
    removeLabels:
    - "status/need-sync"
    failFeedback: "ooops, there are some accidents here, please provide `@req-id` to maintainer to help solve the problem."
---