apiVersion: "v1"
kind: "Repository"
metadata:
  name: "gorda.io"
spec:
  selector:
    owner: "gorda"
    repository: "gorda.io"
  maintainers:
    - "aaa"
    - "bbb"
    - "ccc"
---
apiVersion: "v1"
kind: "IssueCreate"
metadata:
  name: "issue-create"
spec:
  title: "@dir_name"
  body: "path: @path "
  labels:
  - "status/pending"
  - "kind/page"
  assignees:
  - "gorda"
  includes:
#  - path: "content/en/docs/reference/commands"
#    label: "priority/P0"
#  - path: "content/en/docs/reference/config"
#    label: "priority/P0"
  - path: "content/en/docs/"
    label: "priority/P1"
    project: 1 # TODO
    exclude:
    - path: "content/en/docs/reference/commands"
    - path: "content/en/docs/reference/config"
  - path: "content/en/faq/"
    label: "priority/P2"
  - path: "content/en/blog/"
    label: "priority/P3"
  - path: "content/en/news/"
    label: "priority/P3"
  - path: "content/en/about/"
    label: "priority/P4"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-accept"
spec:
  rules:
    instruct: "accept"
    labels:
    - "status/welcome"
    permision:
    - "@maintainer"
    - "@member"
  action:
    addLabels:
    - "status/waiting-for-pushed"
    removeLabels:
    - "status/pending"
    addAssignees:
    - "@commenter"
  feedback:
    success: "xxx"
    fail: "xxx"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-pushed"
spec:
  rules:
    instruct: "pushed"
    labels:
    - "status/waiting-for-pushed"
    permision:
    - "@maintainer"
    - "@assigner"
  action:
    addLabels:
    - "status/waiting-for-update"
    - "status/waiting-for-update"
    removeLabels:
    - "status/waiting-for-pushed"
  feedback:
    success: "xxx"
    fail: "xxx"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-assign"
spec:
  rules:
    instruct: "assign"
    permision:
    - "@maintainer"
  action:
    addAssigneer:
      - "@mention"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-unassign"
spec:
  rules:
    instruct: "unassign"
    permision:
    - "@maintainer"
    - "@assigner" # 对于非 maintainer，仅能 unassign 评论者自己。
  action:
    addLabels:
      - "status/pending"
    removeLabels:
      - "status/waiting-for-pushed"
      - "status/waiting-for-sync"
    removeAssigner:
      - "@mention"
  feedback:
    success: "thanks your your work @mention"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-pushed"
spec:
  labels:
    - "status/accept"
  limit: 10
  assignees:
    - "@commentator"
  success: "thank you ..."
  fail: "sorry ..."
  projects:
    id: 9527
    column: 10086
  # 条件
  rules:
    instruct: "accept"
    permision:
      - "@member"
    assignees:
      - "@commentator"
    labels:
      - "status/pending"
    remove_labels:
      - "status/stale" # /pushed 可移除的 label，但不要求必须存在
    projects:
      id: 9527
      column: 10010
---
apiVersion: "v1"
kind: "Job"
metadata:
  name: "sync"
spec:
  rules:
    labels: # 逻辑或的关系
      - "status/waiting-for-sync"
      - "status/waiting-for-update"
---
apiVersion: "v1"
kind: "Job"
metadata:
  name: "remind"
spec:
  rules:
    labels:
      - "status/waiting-for-update"
    in: 30
  action:
    addLabels:
      - "status/stale"

# 根据对象的属性进行操作和判断。
#
# comment 相关的一些特殊字符
# @somebody @某人
# @count 数量
#
# assign 相关的一些特殊字符
# @remove_all 移除全部
# @keep_all 保留全部
# @remove_specific 移除指定的
# @addition_specific 追加指定的这些

# todo 重构，减少 API 调用时机，提前将 issue 相关数据组合，让代码逻辑清晰一些。
# 优化逻辑，并发
# 日志
