apiVersion: v1
kind: Repository
metadata:
  name: "gorda.io"
spec:
  selector:
    owner: "gorda"
    repository: "gorda.io"
  maintainer:
    - "aaa"
    - "bbb"
    - "ccc"
  token: "xxx"
---
apiVersion: v1
kind: Issue
metadata:
  name: "issue-create"
spec:
  selector:
    owner: "gorda"
    repository: "gorda.io"
  title: "-"
  labels:
  - "status/welcome"
  - "kind/page"
  - "release/v0.3"
  assignees:
  - "noone"
  milestone: 1
---
apiVersion: v1
kind: IssueComment
metadata:
  name: "gorda.io-issue-confirm"
spec:
  selector:
    owner: "gorda"
    repository: "gorda.io"
  labels:
    - "status/pending"
  success: "this issue has ..."
  fail: "sorry ..."
  rules:
    instruct: "confirm"
    permision:
    - "@maintainer"
    labels:
    - "status/welcome"
---
apiVersion: v1
kind: IssueComment
metadata:
  name: "gorda.io-issue-accept"
spec:
  selector:
    owner: "gorda"
    repository: "gorda.io"
  labels:
    - "status/accept"
  # todo 显式的指定添加的 label，移除的 label
  limit: 10
  assignees:
    - "@commentator"
  success: "thank you ..."
  fail: "sorry ..."
  projects:
    id: 9527
    column: 10086
  # 条件
  rules:
    instruct: "accept"
    permision:
      - "@member"
    assignees:
      - "@commentator"
    labels:
      - "status/pending"
    remove_labels:
      - "status/stale" # /pushed 可移除的 label，但不要求必须存在
    projects:
      id: 9527
      column: 10010
---
apiVersion: v1
kind: Job
metadata:
  name: "gorda.io-issue-undo"
spec:
  selector:
    owner: "gorda"
  repository: "gorda.io"
  labels:  # 添加该 label
    - "status/pending"
  remove_labels: # 移除该 label
    - "status/stale"
    - "status/waiting-for-pr"
  assignees:
    - ""
  current_column_id: 9002 # Project 恢复到原来的 column
  target_column_id: 9001
  target_position: "top"
  feedback: "Everyone can accept the issue now."
  rules:
    in: 14
    labels: # 在该状态停留超过一定时间，则释放 issue
      - "status/stale"
---
apiVersion: v1
kind: PullRequest
metadata:
  name: "gorda.io-issue-accept"
spec:
  selector:
    owner: "gorda"
    repository: "gorda.io"
    ...
# 根据对象的属性进行操作和判断。
#
# comment 相关的一些特殊字符
# @somebody @某人
# @count 数量
#
# assign 相关的一些特殊字符
# @remove_all 移除全部
# @keep_all 保留全部
# @remove_specific 移除指定的
# @addition_specific 追加指定的这些

# todo 重构，减少 API 调用时机，提前将 issue 相关数据组合，让代码逻辑清晰一些。
# 优化逻辑，并发
# 日志
