apiVersion: "v1"
kind: "Repository"
metadata:
  name: "3ks.dev"
spec:
  workspace:
    owner: "1kib"
    repository: "new"
  upstream:
    owner: "istio"
    repository: "istio.io"
  commitIssue: 1
  maintainerTeam: "1mib"
  port: ":80"
  logLevel: "dev"
  verbose: false
---
apiVersion: "v1"
kind: "IssueCreate"
metadata:
  name: "issue-create"
spec:
  detection_at: "09:00"
  labels:
  - "status/pending"
  - "kind/page"
  assignees:
  - "3ks"
# milestone: 1
  content: "content/en/"
  includes: # 判断逻辑为包含，而不是前缀
#  - path: "content/en/docs/reference/commands"
#    label: "priority/P0"
#  - path: "content/en/docs/reference/config"
#    label: "priority/P0"
  - path: "_index"
    label: "priority/P0"
  - path: "content/en/docs/"
    label: "priority/P1"
    exclude:
    - path: "content/en/docs/reference/commands"
    - path: "content/en/docs/reference/config"
  - path: "content/en/faq/"
    label: "priority/P2"
  - path: "content/en/blog/"
    label: "priority/P3"
  - path: "content/en/news/"
    label: "priority/P3"
  - path: "content/en/about/"
    label: "priority/P4"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-accept"
spec:
  rules:
    instruct: "accept"
    permision:
    - "@maintainer"
    - "@member"
    permissionFeedback: "sorry"
    labels:
    - "status/pending"
    labelFeedback: "sorry"
  action:
    addLabels:
    - "status/waiting-for-update"
    addLabelsLimit: 10
    labelLimitFeedback: "sorry"
    removeLabels:
    - "status/pending"
    addAssignees:
    - "@commenter"
    successFeedback: "thank you"
    failFeedback: "sorry"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-sync"
spec:
  rules:
    instruct: "synced"
    permision:
    - "@maintainer"
    - "@member"
    permissionFeedback: "sorry"
    labels:
    - "status/waiting-for-sync"
    labelFeedback: "sorry"
  action:
    addLabels:
    - "status/waiting-for-update"
    labelLimitFeedback: "sorry"
    removeLabels:
    - "status/waiting-for-sync"
    - "status/stale"
    successFeedback: "thank you"
    failFeedback: "sorry"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-wavier"
spec:
  rules:
    instruct: "wavier"
    permision:
    - "@maintainer"
    - "@member"
    labels:
    - "status/waiting-for-sync"
    labelFeedback: "sorry"
  action:
    addLabels:
    - "status/pending"
    removeLabels:
    - "status/waiting-for-sync"
    - "status/waiting-for-update"
    - "status/stale"
    removeAssigners:
    - "@all"
    successFeedback: "thank you"
    failFeedback: "sorry"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-assign"
spec:
  rules:
    instruct: "assign"
    permision:
    - "@maintainer"
  action:
    addAssigneer:
    - "@mention"
---
apiVersion: "v1"
kind: "IssueComment"
metadata:
  name: "issue-unassign"
spec:
  rules:
    instruct: "unassign"
    permision:
    - "@maintainer"
    - "@assigner" # 对于非 maintainer，仅能 unassign 评论者自己。
  action:
    removeAssigner:
    - "@mention"
---
apiVersion: "v1"
kind: "Job"
metadata:
  name: "remind"
spec:
  rules:
    in: 30
    labels:
    - "status/waiting-for-sync"
    addLabels:
    - "status/stale"

# 根据对象的属性进行操作和判断。
#
# comment 相关的一些特殊字符
# @somebody @某人
# @count 数量
#
# assign 相关的一些特殊字符
# @remove_all 移除全部
# @keep_all 保留全部
# @remove_specific 移除指定的
# @addition_specific 追加指定的这些

# todo 重构，减少 API 调用时机，提前将 issue 相关数据组合，让代码逻辑清晰一些。
# 优化逻辑，并发
# 日志
#      accept                synced
# pending/waiting-for-sync(stale)/synced/description
#                      waive
