full_repository_name: "gorda/gorda.io"
maintains:
  - "gorda"
flows:
  # /accept 指令
  - name: "/accept"
    permission:
      - "maintainers"
      - "member"
    current_label:
      - "status/pending"
    target_label:
      - "status/waiting-for-pr"
    success_feedback: "Thank you @somebody, this issue had been assigned to you."

  # /pushed 指令
  - name: "/pushed"
    permission:
      - "maintainers"
      - "self"
    current_label:
      - "status/waiting-for-pr"
    target_label:
      - "status/reviewing"

  # /merged 指令
  - name: "/merged"
    permission:
      - "maintainers"
      - "self"
    current_label:
      - "status/reviewing"
    target_label:
      - "status/merged"
    close: true